## **데이터 구조 파악하기**
**데이터 분석의 출발점으로, 구조 파악 없이는 분석 전 과정에서 오류와 비효율이 발생할 수 있음.**

**1) 적합한 분석 방법 선택**
- 데이터 형식에 따라 적절한 분석 방법이 달라짐.
- 예를 들어, 숫자형 데이터는 평균과 표준편차를, 범주형 데이터는 빈도수를 분석하는 것이 효과적임.

**2) 오류 방지**
- 데이터 구조를 제대로 이해하지 않으면 타입 오류나 결측치로 인한 문제가 발생할 수 있음.
- 예를 들어, 범주형 데이터를 숫자형으로 잘못 처리하면 분석 오류로 이어질 수 있음.

**3) 데이터 전처리 효율성 향상**
- 데이터 구조를 파악하면 결측치, 이상치 등을 미리 처리하여 전처리 시간을 절약하고, 분석 결과의 신뢰도를 높일 수 있음.

## **데이터를 불러오면 확인해야 하는 것**
- **1. 데이터 구조(정형데이터모델)** 
    - index(데이터 순서, 데이터 갯수)
    - column (데이터 항목, 데이터 타입 - 숫자 데이터, 문자 데이터)
    - value (데이터의 값)
- **2. 데이터 타입 :** 데이터 타입에 따라서 통계 분석 기법이 달라짐
    - 연속형 (숫자) : int 정수형, float 실수형
    - 범주형 (문자) : object

In [2]:
import pandas as pd

In [3]:
# 데이터 불러오기
df = pd.read_csv('./01_Contract_Data.csv')

#### **columns / index, shape 열 이름과 인덱스, 데이터 크기 확인**

In [4]:
# columns 데이터 프레임 내 항목 확인
df.columns

Index(['Index', 'Member_ID', 'Sales_Type', 'Contract_Type', 'Channel',
       'Datetime', 'Term', 'Payment_Type', 'Product_Type', 'Amount_Month',
       'Customer_Type', 'Age', 'Address1', 'Address2', 'State',
       'Overdue_count', 'Overdue_Type', 'Gender', 'Credit_Rank', 'Bank'],
      dtype='object')

In [5]:
# index 데이터 프레임이 총 몇행으로 구성되어 있는지
df.index

RangeIndex(start=0, stop=51301, step=1)

In [6]:
# shape 데이터 크기 확인, 행과 열의 개수를 반환
df.shape

(51301, 20)

**info(): 데이터 구조와 각 열의 정보 확인**
- DataFrame의 전체적인 정보를 제공함. 각 열의 데이터 타입, 누락된 값의 개수, 데이터 크기 등을 포함함

In [7]:
# info() DataFrame의 전체적인 정보
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51301 entries, 0 to 51300
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          51301 non-null  int64
 1   Member_ID      51301 non-null  int64
 2   Sales_Type     51301 non-null  object
 3   Contract_Type  51301 non-null  object
 4   Channel        51301 non-null  object
 5   Datetime       51301 non-null  object
 6   Term           51301 non-null  int64
 7   Payment_Type   51301 non-null  object
 8   Product_Type   51301 non-null  object
 9   Amount_Month   51301 non-null  int64
 10  Customer_Type  51299 non-null  object
 11  Age            44329 non-null  float64
 12  Address1       51299 non-null  object
 13  Address2       51299 non-null  object
 14  State          51301 non-null  object
 15  Overdue_count  51301 non-null  int64
 16  Overdue_Type   51301 non-null  object
 17  Gender         51301 non-null  object
 18  Credit_Rank    42520 non-null  float64
 19  Bank           48542 non-null  object
dtypes: float64(2), int64(5), object(13)
memory usage: 7.8+ MB

**데이터의 일부 미리보기**
- head(): 상위 몇 개의 행을 미리보기 함. 기본적으로 처음 5개의 행을 반환함.
- tail(): 하위 몇 개의 행을 미리보기 함.

In [8]:
# head() 데이터 프레임 상위 행을 보여줌, 기본 5개행
df.head()

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합

In [80]:
# tail() 데이터 프레임 하위 행을 보여줌, 기본 5개행
df.tail()

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,개인,47.0,경기도,경기도,계약확정,0,없음,남자,NaN,기업은행
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,8.0,새마을금고
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,개인,54.0,서울특별시,서울특별시,계약확정,0,없음,여자,2.0,롯데카드
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,개인,53.0,서울특별시,서울특별시,계약확정,0,없음,여자,8.0,신한은행

## **숫자 데이터 - 기술 통계 분석(DDA)**

- 숫자 데이터는 데이터의 중심 경향, 분포, 변동성 등을 파악하는 것이 중요함. 
- 대표값과 산포도를 확인하여 데이터의 특징을 이해할 수 있음.

**주요 사항**
- 대표값: 평균, 중앙값, 최빈값 등 데이터의 중심을 나타내는 값.
- 산포도: 데이터가 얼마나 흩어져 있는지를 나타내는 값. 분산, 표준편차 등을 확인.
- 분포: 데이터가 어떤 분포를 따르는지 파악. 최소값, 최대값, 분위수 등을 통해 데이터의 범위를 확인.
- 상관관계: 숫자형 데이터 간의 관계를 파악. 상관계수로 두 변수 간의 연관성을 확인.

#### **대표값** : 데이터의 중심을 나타내는 값으로, 데이터의 전반적인 특징을 요약하는 데 사용됨
- **평균 (mean()) :** 데이터의 산술 평균을 계산함. 데이터 전체를 합한 후 데이터 개수로 나눈 값
- **중앙값 (median()) :** 데이터를 크기 순서대로 정렬했을 때 가운데 위치한 값임. 평균이 이상치에 영향을 받을 때, 중앙값은 데이터의 중심 경향을 더 잘 나타냄
- **최빈값 (mode()) :** 데이터에서 가장 자주 등장하는 값임. 특히 범주형 데이터에서 유용하지만, 숫자형 데이터에서도 최빈값을 확인할 수 있음
#### **산포도** : 데이터가 평균을 중심으로 얼마나 흩어져 있는지, 즉 데이터의 변동성을 나타냄. 
- **분산 (Variance, var()) :** 분산은 데이터가 평균으로부터 얼마나 퍼져 있는지를 나타내는 값임. 데이터와 평균의 차이를 제곱하여 평균낸 값임.
- **표준편차 (Standard Deviation, std()) :** 분산의 제곱근을 취한 값으로, 데이터의 흩어짐 정도를 나타냄. 값이 클수록 데이터가 평균에서 많이 퍼져 있음을 의미함
#### **데이터의 범위와 분포** : 숫자 데이터의 최소값, 최대값, 분위수(quantile) 등을 확인하여 데이터가 어떻게 분포되어 있는지 파악함. 
- **최소값 (min, min())**: 데이터에서 가장 작은 값을 반환.
- **최대값 (max, max())**: 데이터에서 가장 큰 값을 반환.
- **분위수 (Quantiles, quantile())** : 데이터의 특정 백분위수를 계산함. 예를 들어, **0.25 분위수(1사분위)**는 데이터의 하위 25%에 해당하는 값임
- **사분위 범위 (IQR - Interquartile Range)** : 사분위 범위는 데이터의 중앙 50%에 해당하는 값의 범위를 나타냄. 3사분위(75%)에서 1사분위(25%)를 뺀 값임
- **첨도(Kurtosis, kurt())** : 데이터 분포의 꼬리 두께를 측정하는 값임. 첨도는 분포가 얼마나 뾰족한지 또는 평평한지를 나타냄. 정규 분포의 첨도는 3에 가까움
- **왜도(Skewness, skew())** : 는 데이터의 비대칭성을 나타내는 통계 값임. 정규 분포는 왜도가 0

### **대표값**

In [5]:
# 특정 컬럼 선택, DataFrame.['컬럼명'] => Series 형태
df['Term']

0        60
1        60
2        60
3        12
4        12
         ..
51296    60
51297    60
51298    39
51299    60
51300    60
Name: Term, Length: 51301, dtype: int64

In [97]:
# mean() : 평균 값 확인
df['Term'].mean()
df['Amount_Month'].mean()

93994.97428900021

In [98]:
# sum() : 데이터의 합 확인
df['Amount_Month'].sum()

4822036176

In [99]:
# median() : 중앙값
df['Amount_Month'].median()

96900.0

In [100]:
# mode() : 최빈값
df['Amount_Month'].mode()

0    96900
Name: Amount_Month, dtype: int64

### **산포도**

In [106]:
# var() : 표본 분산 / 모집단 분산 var(ddof=0)
df['Amount_Month'].var()

234220496.22895092

In [104]:
# std() : 표본 표준 편차 / 모집단 표준 편차 std(ddof=0)
df['Amount_Month'].std()

15304.263988475595

### **데이터 범위와 분포**

In [128]:
# min(), max() 최소, 최댓값
min = df['Amount_Month'].min()
min

54603

In [129]:
max = df['Amount_Month'].max()
max

215700

In [132]:
# 데이터 범위
range = max - min
range

161097

In [125]:
# 사분위수 구하기 quantile()
q1 = df['Amount_Month'].quantile(0.25)
q2 = df['Amount_Month'].quantile(0.50)
q3 = df['Amount_Month'].quantile(0.75)
print(q1, q2, q3)

81900.0 96900.0 98400.0

In [124]:
# 사분위 범위
IQR = q3 - q1
IQR

16500.0

### **describe() 함수**
- 데이터의 기본 통계량을 요약하여 제공함. 숫자형 데이터에 대해 **평균, 표준편차, 최소값, 최대값, 분위수(25%, 50%, 75%)**를 확인할 수 있음.

In [28]:
# DataFrame의 숫자 데이터의 요약 통계량 제공
df.describe() # 요약통계량

,Index,Member_ID,Term,Amount_Month,Age,Overdue_count,Credit_Rank
count,51301.000000,5.130100e+04,51301.000000,51301.000000,44329.000000,51301.000000,42520.000000
mean,25651.703612,6.266432e+07,55.639149,93994.974289,50.024093,0.161381,3.428810
std,14809.828628,1.216146e+07,12.009915,15304.263988,10.983877,1.122193,2.213453
min,1.000000,2.568798e+07,12.000000,54603.000000,25.000000,0.000000,0.000000
25%,12826.000000,6.643148e+07,60.000000,81900.000000,42.000000,0.000000,1.000000
50%,25652.000000,6.676578e+07,60.000000,96900.000000,49.000000,0.000000,3.000000
75%,38477.000000,6.678160e+07,60.000000,98400.000000,57.000000,0.000000,5.000000
max,51302.000000,6.696986e+07,60.000000,215700.000000,102.000000,15.000000,10.000000

## **범주형 데이터**

- **항목과 빈도**
- 문자 데이터를 확인할 때, 숫자형 데이터와는 다르게 **고유값, 빈도수, 길이**와 같은 특성을 주로 살펴보게 됨.
- 문자 데이터의 데이터 구조를 파악하는 과정에서는 **데이터 타입 확인, 고유값 확인, 빈도수 계산, 문자열 길이** 등을 확인

#### **갯수, 최빈값, 고유값(항목)과 빈도(갯수) 확인**
- count() : 데이터의 갯수
- mode() : 최빈값
- unique() : 고유값 / nunique() : 고유값의 갯수
- value_counts() : 빈도 수(객수) - Frequency / 상대 빈도 : 각 범주의 비율  normalize=True

In [31]:
# count() : 데이터의 개수
df['Bank'].count()

48542

In [ ]:
# mode()최빈값
df['Bank'].mode()

In [11]:
# 고유값 확인 unique(): 특정 열의 고유값
df['Sales_Type'].unique()

array(['렌탈', '멤버십'], dtype=object)

In [14]:
# 고객들이 어떤 수단으로 결재하는지, 어떤 은행으로 결재하는 지
df['Bank'].unique()

array(['새마을금고', '현대카드', '우리은행', '농협회원조합', '농협중앙회', '롯데카드', '신한은행', '국민카드',
       '부산은행', '우체국', '국민은행', '기업은행', 'SC제일은행', nan, '대구은행', '하나은행',
       '신한카드', '삼성카드', '광주은행', '외환은행', 'BC카드', '씨티은행', '신협중앙회', '경남은행',
       '미래에셋증권', '외환카드', '수협중앙회', '유안타증권', '전북은행', '상호저축은행', '대신증권',
       '산업은행', '현대증권', '산림조합중앙회', '제주은행', '삼성증권', '하나대투증권', 'SK증권',
       '수협카드', '한국투자증권', '신한금융투자', '하나SK', 'NH농협카드', '메리츠종합금융증권',
       '하이투자증권', '우리카드', '대우증권', '씨티카드'], dtype=object)

In [15]:
# 빈도 수 확인 value_counts(): 각 항목별 갯수
df['Bank'].value_counts()

Bank
롯데카드         9516
농협회원조합       6277
국민은행         6002
농협중앙회        3899
신한은행         3522
우리은행         3386
기업은행         1963
신한카드         1532
하나은행         1446
국민카드         1311
BC카드         1264
새마을금고         964
부산은행          889
삼성카드          884
현대카드          876
대구은행          746
우체국           718
외환은행          586
외환카드          530
경남은행          442
SC제일은행        439
광주은행          347
신협중앙회         341
전북은행          195
씨티은행          162
수협중앙회         160
제주은행           40
유안타증권          27
산업은행           23
현대증권           11
삼성증권            7
하나SK            6
미래에셋증권          5
한국투자증권          4
신한금융투자          4
NH농협카드          4
우리카드            3
대우증권            2
산림조합중앙회         1
대신증권            1
하나대투증권          1
SK증권            1
수협카드            1
상호저축은행          1
메리츠종합금융증권       1
하이투자증권          1
씨티카드            1
Name: count, dtype: int64

In [ ]:
# 상대 빈도 : normalize = True
df['Bank'].value_counts(normalize=True)

#### **describe() 함수를 사용할 수 있음**. 
- 숫자형 데이터와 달리 문자 데이터의 경우 다음과 같은 통계 정보가 제공됨:
- count: 데이터 개수.
- unique: 고유값 개수.
- top: 가장 많이 등장한 값.
- freq: 가장 많이 등장한 값의 빈도수.

In [25]:
# describe() : 특정열 기준으로 기초 통계량 제공 
df['Bank'].describe()

count     48542
unique       47
top        롯데카드
freq       9516
Name: Bank, dtype: object

In [27]:
# DataFrame.decribe : 파라미터 include='object'일 경우 데이터 프레임의 문자 데이터 통계량
df.describe(include='object')

,Sales_Type,Contract_Type,Channel,Datetime,Payment_Type,Product_Type,Customer_Type,Address1,Address2,State,Overdue_Type,Gender,Bank
count,51301,51301,51301,51301,51301,51301,51299,51299,51299,51301,51301,51301,48542
unique,2,9,16,577,5,6,2,8,14,4,2,2,47
top,렌탈,프로모션계약,영업방판,2019-01-31,CMS,DES-1,개인,경기도,경기도,계약확정,없음,여자,롯데카드
freq,46483,15811,23767,1167,32825,39133,46263,18353,14883,50620,49110,35602,9516