1. 판다스 라이브러리 임포트 하고 csv 파일 불러오기
2. 데이터 구조 파악하기
3. vip 회원들 중 모바일 알람 신청한 분들 대상으로 사은품 증정, 사은품 선정을 위한 데이터 분석과 고객 명단 필요(excel 파일로 저장)

In [1]:
# 라이브러리 불러오기
import pandas as pd

In [25]:
# 데이터 불러오기
df = pd.read_csv('./02_VIP_member_Data.csv')
df

,ID,State,Address,Gender,Age,총구매금액,총구매수량,1회방문시구매금액(평균),배송서비스신청여부,모바일알람여부,VIP회원
0,272369856,정상회원,수지구,여,45.0,5733884,546.5,47782,미신청,수신,VIP
1,1506656256,정상회원,수지구,여,36.0,673414,90.0,35443,미신청,.,normal
2,1476143616,정상회원,수지구,여,34.0,655919,66.0,46851,미신청,.,normal
3,716128320,정상회원,수지구,여,51.0,2984534,252.1,48138,미신청,.,normal
4,743192512,정상회원,수지구,여,51.0,1901488,152.0,158457,신청,.,normal
...,...,...,...,...,...,...,...,...,...,...,...
6514,1645334720,정상회원,수지구,남,32.0,52646,1.1,52646,미신청,.,normal
6515,963408768,정상회원,분당구,여,46.0,61740,9.0,61740,미신청,.,normal
6516,309812800,정상회원,기타,여,82.0,15507,2.0,15507,미신청,.,normal
6517,96714304,정상회원,분당구,여,55.0,36374,2.0,36374,미신청,.,normal
6518,1547170880,정상회원,기타,남,41.0,15890,1.0,15890,미신청,.,normal

In [4]:
# 데이터 구조 파악 하기
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6519 entries, 0 to 6518
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             6519 non-null   int64
 1   State          6519 non-null   object
 2   Address        6519 non-null   object
 3   Gender         6518 non-null   object
 4   Age            6518 non-null   float64
 5   총구매금액          6519 non-null   int64
 6   총구매수량          6519 non-null   float64
 7   1회방문시구매금액(평균)  6519 non-null   int64
 8   배송서비스신청여부      6519 non-null   object
 9   모바일알람여부        6519 non-null   object
 10  VIP회원          6519 non-null   object
dtypes: float64(2), int64(3), object(6)
memory usage: 560.4+ KB

In [5]:
df.columns

Index(['ID', 'State', 'Address', 'Gender', 'Age', '총구매금액', '총구매수량',
       '1회방문시구매금액(평균)', '배송서비스신청여부', '모바일알람여부', 'VIP회원'],
      dtype='object')

In [7]:
df['VIP회원'].unique()

array(['VIP', 'normal'], dtype=object)

In [6]:
df['VIP회원'].value_counts()

VIP회원
normal    6423
VIP         96
Name: count, dtype: int64

In [8]:
df['모바일알람여부'].unique()

array(['수신', '.'], dtype=object)

In [9]:
df['모바일알람여부'].value_counts()

모바일알람여부
.     6016
수신     503
Name: count, dtype: int64

In [13]:
# 데이터 필터링
조건1 = (df['VIP회원']=='VIP')
조건2 = (df['모바일알람여부']=='수신')

In [15]:
# vip이면서 모바일 알람 수신한 고객
df_vip = df.loc[조건1 & 조건2]
df_vip

,ID,State,Address,Gender,Age,총구매금액,총구매수량,1회방문시구매금액(평균),배송서비스신청여부,모바일알람여부,VIP회원
0,272369856,정상회원,수지구,여,45.0,5733884,546.5,47782,미신청,수신,VIP
10,1343359808,정상회원,수지구,여,49.0,13894023,1574.0,100681,미신청,수신,VIP
11,757812224,정상회원,수지구,여,55.0,12637762,1528.2,70999,미신청,수신,VIP
20,383356800,정상회원,수지구,여,47.0,8882881,1112.2,60842,미신청,수신,VIP
26,744736704,정상회원,수지구,여,49.0,8326962,673.5,57427,미신청,수신,VIP
...,...,...,...,...,...,...,...,...,...,...,...
1389,748077504,정상회원,수지구,여,57.0,8725977,805.0,87260,미신청,수신,VIP
1416,1549429632,정상회원,수지구,여,53.0,5197635,652.0,24989,미신청,수신,VIP
1435,20588608,정상회원,수지구,여,51.0,11056842,886.3,85053,미신청,수신,VIP
1489,264533824,정상회원,분당구,여,58.0,5834274,510.5,47822,미신청,수신,VIP
3217,125287424,정상회원,수지구,여,49.0,14666195,1560.4,81029,미신청,수신,VIP

In [17]:
# 데이터 파일로 저장
df_vip.to_excel('vip_alert_member.xlsx')

4. VIP회원 중 총 구매가격이 낮은 상위 10명의 고객 확인하고 csv 파일로 만들기
5. 지역을 입력하면 지역의 vip 고객명단을 추출해서 csv 파일로 만들어주는 코드 작성
6. 연령 범위를 입력하면 해당 연령 구간의 회원을 출력해주고 파일로 만들어주는 코드

In [26]:
# 4. VIP회원 중 총 구매가격이 낮은 상위 10명의 고객 확인하고 csv 파일로 만들기
cond = df['VIP회원'] == 'VIP'
df_sort = df[cond].sort_values(by='총구매금액')
df_sort.head(10)

,ID,State,Address,Gender,Age,총구매금액,총구매수량,1회방문시구매금액(평균),배송서비스신청여부,모바일알람여부,VIP회원
853,116573504,정상회원,수지구,여,51.0,2497794,313.00,24978,미신청,수신,VIP
445,1238555200,정상회원,분당구,여,65.0,2741376,413.00,25383,미신청,.,VIP
1272,1059544000,정상회원,수지구,여,50.0,2939392,441.00,21613,미신청,수신,VIP
1082,1340139648,정상회원,수지구,여,38.0,3386088,412.00,30505,미신청,수신,VIP
884,797296768,정상회원,수지구,여,60.0,3429622,404.16,33297,미신청,.,VIP
950,896089792,정상회원,수지구,여,55.0,3504908,697.10,34028,미신청,수신,VIP
53,768526912,정상회원,수지구,여,45.0,3637990,476.60,25620,미신청,수신,VIP
391,59759488,정상회원,수지구,여,69.0,3997355,506.30,33311,미신청,.,VIP
79,282238208,정상회원,수지구,여,73.0,4205036,434.00,39299,미신청,.,VIP
246,918586368,정상회원,수지구,여,41.0,4336244,432.00,40908,미신청,수신,VIP

In [28]:
# 5. 지역을 입력하면 지역의 vip 고객명단을 추출해서 csv 파일로 만들어주는 코드 작성
지역 = input('지역을 입력하세요 : ')

cond1 = df['VIP회원'] == 'VIP'
cond2 = df['Address'] == 지역

df.loc[cond1 & cond2].to_csv(f'{지역}_vip.csv')

지역을 입력하세요 :  수지구

In [30]:
지역 = input('지역을 입력하세요 : ')
df2 = pd.read_csv(f'./{지역}_vip.csv')
df2.head()

지역을 입력하세요 :  수지구

,Unnamed: 0,ID,State,Address,Gender,Age,총구매금액,총구매수량,1회방문시구매금액(평균),배송서비스신청여부,모바일알람여부,VIP회원
0,0,272369856,정상회원,수지구,여,45.0,5733884,546.5,47782,미신청,수신,VIP
1,5,176912064,정상회원,수지구,여,69.0,8028076,716.0,62719,미신청,.,VIP
2,10,1343359808,정상회원,수지구,여,49.0,13894023,1574.0,100681,미신청,수신,VIP
3,11,757812224,정상회원,수지구,여,55.0,12637762,1528.2,70999,미신청,수신,VIP
4,20,383356800,정상회원,수지구,여,47.0,8882881,1112.2,60842,미신청,수신,VIP

In [35]:
# 6. 연령 범위를 입력하면 해당 연령 구간의 회원을 출력해주고 파일로 만들어주는 코드

In [34]:
연령_최소값 = int(input(' 연령 범위를 입력(최소값) : '))
연령_최대값 = int(input(' 연령 범위를 입력(최대값) : '))

cond = df['Age'].between(연령_최소값, 연령_최대값)
df3 = df.loc[cond]
df3.to_csv("연령별_member.csv")

 연령 범위를 입력(최소값) :  30
 연령 범위를 입력(최대값) :  50